# -*- coding: utf-8 -*-
"""_CNN_Moto_Car_GoogleDrive_BM_45min.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ebYBasew2RfaKGkPojBugwcleZv_zF9q

<div style='background:#081321;color:#F8FAFC;padding:26px;border-radius:18px;border-left:8px solid #22D3EE;border-bottom:3px solid #76B900;'>
<p style='margin:0;color:#22D3EE;font-size:12px;font-weight:bold;letter-spacing:2px;'>JETSON AI BOX • KV-TRON CNN • PYTORCH</p>
<div style='float:right;background:#11212F;border:1px solid #22D3EE;color:#22D3EE;padding:7px 11px;border-radius:8px;font-family:monospace;font-weight:bold;'>[ REAL IMAGE VISION TRAINING ]</div>
<h1 style='margin:18px 0 4px 0;color:#FFFFFF;'>BAHAGIAN 4</h1>
<h2 style='margin:0 0 14px 0;color:#FFFFFF;'>Cats vs Dogs with Google Drive: Train KV-TRON with Real Images</h2>
<p style='margin:0;color:#E5E7EB;'>Tempoh sasaran: <b>45 minit</b> | Platform: <b>Google Colab (.ipynb)</b></p>
</div>

# Mission Scenario
KV-TRON kini perlu mengenali imej sebenar `cats` dan `dogs`.

## Dataset Folder Requirement
```text
KVTRON_CNN_Dataset/
├── train/
│   ├── cats/
│   └── dogs/
└── test/
    ├── cats/
    └── dogs/
```

# 1. Mount Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""# 2. FIX ME: Set Dataset Path"""

import os

dataset_path = "FIX_ME"  # contoh: "/content/drive/MyDrive/KVTRON_CNN_Dataset"

if dataset_path == "FIX_ME":
    print("[BELUM LENGKAP] Gantikan dataset_path dengan lokasi folder sebenar.")
else:
    train_dir = dataset_path + "/train"
    test_dir = dataset_path + "/test"
    print("Train folder exists:", os.path.exists(train_dir))
    print("Test folder exists :", os.path.exists(test_dir))
    if os.path.exists(train_dir): print("Train classes:", os.listdir(train_dir))
    if os.path.exists(test_dir): print("Test classes :", os.listdir(test_dir))

import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

torch.manual_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Peranti digunakan:", device)

"""# 3. Image Transform"""

train_transform = transforms.Compose([
    transforms.Resize((64, 64)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor()
])

test_transform = transforms.Compose([
    transforms.Resize((64, 64)),
    transforms.ToTensor()
])
print("[SEDIA] Image transforms telah ditetapkan.")

"""# 4. Load Dataset with ImageFolder"""

if "train_dir" not in globals() or "test_dir" not in globals():
    print("[BELUM SEDIA] Lengkapkan dataset_path dahulu.")
    train_dataset = test_dataset = None
else:
    train_dataset = datasets.ImageFolder(root=train_dir, transform=train_transform)
    test_dataset = datasets.ImageFolder(root=test_dir, transform=test_transform)
    print("Class names     :", train_dataset.classes)
    print("Class mapping   :", train_dataset.class_to_idx)
    print("Training images :", len(train_dataset))
    print("Testing images  :", len(test_dataset))

"""# 5. Create DataLoader and Visualise Samples"""

if train_dataset is None or test_dataset is None:
    print("[BELUM SEDIA] Load dataset dahulu.")
    train_loader = test_loader = None
else:
    train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)
    images, labels = next(iter(train_loader))
    print("Batch image shape:", images.shape)
    print("Batch label shape:", labels.shape)
    plt.figure(figsize=(10,4))
    for i in range(min(4, len(images))):
        image = images[i].permute(1,2,0)
        class_name = train_dataset.classes[labels[i].item()]
        plt.subplot(1,4,i+1)
        plt.imshow(image)
        plt.title(class_name)
        plt.axis("off")
    plt.show()

"""# 6. FIX ME: Build CatDogCNN Model"""

INPUT_CHANNELS = None
OUTPUT_CLASSES = None

class CatDogCNN(nn.Module):
    def __init__(self):
        super().__init__()
        if INPUT_CHANNELS is None or OUTPUT_CLASSES is None:
            raise ValueError("Lengkapkan INPUT_CHANNELS dan OUTPUT_CLASSES dahulu.")
        self.features = nn.Sequential(
            nn.Conv2d(INPUT_CHANNELS, 16, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(16, 32, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(32, 64, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2)
        )
        self.classifier = nn.Sequential(
            nn.Flatten(), nn.Linear(64 * 8 * 8, 128), nn.ReLU(), nn.Linear(128, OUTPUT_CLASSES)
        )
    def forward(self, x):
        return self.classifier(self.features(x))

try:
    model = CatDogCNN().to(device)
    print(model)
except Exception as e:
    model = None
    print("[BELUM LENGKAP]", e)

"""# 7. FIX ME: Training Setup"""

if model is None:
    print("[BELUM SEDIA] Lengkapkan model dahulu.")
    criterion = optimizer = epochs = None
else:
    criterion = None   # FIX ME: nn.CrossEntropyLoss()
    optimizer = None   # FIX ME: optim.Adam(model.parameters(), lr=0.001)
    epochs = None      # FIX ME: 3
    if criterion is None or optimizer is None or epochs is None:
        print("[BELUM LENGKAP] Lengkapkan criterion, optimizer dan epochs.")

"""# 8. Train Model"""

if model is None or train_loader is None or criterion is None or optimizer is None or epochs is None:
    print("[BELUM SEDIA] Lengkapkan dataset, model dan training setup dahulu.")
    training_complete = False
else:
    for epoch in range(epochs):
        model.train(); running_loss = 0.0; correct = 0; total = 0
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
            predicted = torch.argmax(outputs, dim=1)
            correct += (predicted == labels).sum().item(); total += labels.size(0)
        accuracy = correct / total if total else 0
        print(f"Epoch {epoch+1}/{epochs}: Loss={running_loss:.4f}, Accuracy={accuracy:.4f}")
    training_complete = True

"""# 9. Evaluate and Predict"""

if not globals().get("training_complete", False):
    print("[BELUM SEDIA] Train model dahulu.")
else:
    model.eval(); correct = 0; total = 0
    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            predicted = torch.argmax(outputs, dim=1)
            correct += (predicted == labels).sum().item(); total += labels.size(0)
    test_accuracy = correct / total if total else 0
    print("Test Accuracy:", f"{test_accuracy:.4f}")
    image, actual_label = test_dataset[0]
    with torch.no_grad():
        output = model(image.unsqueeze(0).to(device))
        predicted_label = torch.argmax(output, dim=1).item()
    predicted_class = test_dataset.classes[predicted_label]
    actual_class = test_dataset.classes[actual_label]
    plt.figure(figsize=(4,4))
    plt.imshow(image.permute(1,2,0))
    plt.title(f"Predicted: {predicted_class} | Actual: {actual_class}")
    plt.axis("off")
    plt.show()
    print("Predicted:", predicted_class)
    print("Actual   :", actual_class)

import os
import torch

save_dir = "/content/drive/MyDrive/Colab Notebooks"
save_path = os.path.join(save_dir, "kvtron_catdog_cnn_model.pth")

if globals().get("training_complete", False):
    os.makedirs(save_dir, exist_ok=True)

    torch.save(model.state_dict(), save_path)

    print("Model disimpan sebagai:", save_path)
else:
    print("Model belum disimpan kerana training_complete masih False.")

"""# Reflection Bahagian 4
1. Mengapa Cat/Dog images menggunakan `Conv2d(3,...)`?  
   **Jawapan:**  
2. Mengapa dataset perlu disusun dalam folder `train/cats`, `train/dogs`, `test/cats`, `test/dogs`?  
   **Jawapan:**  
3. Mengapa semua imej perlu di-resize kepada `64 x 64`?  
   **Jawapan:**  
4. Apakah fungsi `RandomHorizontalFlip()`?  
   **Jawapan:**  
5. Mengapa accuracy mungkin rendah jika dataset kecil?  
   **Jawapan:**

# Checkpoint Bahagian 4
| Evidence | Status |
|---|---|
| Google Drive mounted | ☐ |
| Dataset path detected | ☐ |
| `cats` and `dogs` folders detected | ☐ |
| ImageFolder loaded | ☐ |
| Class mapping displayed | ☐ |
| Sample images visualised | ☐ |
| CatDogCNN model printed | ☐ |
| Training loss displayed | ☐ |
| Test accuracy displayed | ☐ |
| One prediction visualised | ☐ |
"""